// /Users/i_kawano/Documents/portfolio/components/Header.figma.tsx
import React from 'react';
import Header from '../compositions/Header';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(Header, 'https://www.figma.com/design/LGX4rWgjTHK5smLM34T4o0/portfolio?node-id=1%3A5063', {
  props: {},
  example: (props) => <Header />,
});
